# Retrieve all facilities of a particular set of industries (for example, all power generation facilities as indicated by the four-digit NAICS code 2211). Group them by their most specific industry code and count how many exist of that code.


PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX fio: <http://w3id.org/fio/v1/fio#>
PREFIX naics: <http://w3id.org/fio/v1/naics#> 
PREFIX epa-frs: <http://w3id.org/fio/v1/epa-frs#>

select ?code ?code_label (Count(?facility) as ?no_facilities)
where {
        ?facility rdf:type epa-frs:EPA-PFAS-Facility ;
    		fio:ofIndustry ?code .
        	?code 	fio:subcodeOf ?icode ;
    				rdfs:label ?code_label .
    	VALUES ?icode{naics:NAICS-2211}
} group by ?code ?code_label 
limit 100
