# Get all facilities from a specific industry sector or group and list all their specific industry codes as a concatenated list 

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fio: <http://w3id.org/fio/v1/fio#>
PREFIX naics: <http://w3id.org/fio/v1/naics#>


select ?facility (concat('[',group_concat(DISTINCT ?industry;separator='; '),']') as ?industries) where  {{
    SERVICE <repository:FIO> {{
    	?facility a fio:Facility .
    	?facility fio:ofIndustry ?industry.
      ?industry fio:subcodeOf naics:NAICS-3222. #Converted Paper Manufacturing
      ?facility kwg-ont:sfWithin ?s2.
    }}
     SERVICE <repository:Spatial>
    {{
        # Basic classification of spatial entities (e.g. S2 cells, admin regions) should be added to the FIO repository to allow querying without federation
		?s2 a kwg-ont:S2Cell_Level13.

    }}
    }} GROUP BY ?facility
