# FIO Basics
# CQ 5
# Retrieve the NAICS Industry Code and other classifications (Sector, Subsector, Group) of a specific facility.
# 2024-09-30 Update: Using the fio:ofIndustry property chain axiom

PREFIX fio: <http://w3id.org/fio/v1/fio#>
PREFIX naics: <http://w3id.org/fio/v1/naics#> 
PREFIX epa-frs-data: <http://w3id.org/fio/v1/epa-frs-data#>

select * where {
    epa-frs-data:d.FRS-Facility.110000428662 fio:ofIndustry ?o .
} 


# FIO Basics
# CQ 5b
# Retrieve the NAICS Industry Codes of all facilities in NAICS sector 32.
# Works without relying on the fio:ofIndustry property chain axiom


PREFIX fio: <http://w3id.org/fio/v1/fio#>
PREFIX naics: <http://w3id.org/fio/v1/naics#> 

select * where {
    ?f fio:ofIndustry ?o .
    ?o fio:subcodeOf naics:NAICS-32 .
} limit 100

