# FIO Basics
# CQ 5
# Retrieve the NAICS Industry Code and other classifications (Sector, Subsector, Group) of a specific facility (here: facilities with FRS ID 110000428662).
# 2024-09-30 Update: Using the fio:ofIndustry property chain axiom
# 2026-03-09 Update: Retrieve label of the NAICS codes as well

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fio: <http://w3id.org/fio/v1/fio#>
PREFIX naics: <http://w3id.org/fio/v1/naics#> 
PREFIX epa-frs-data: <http://w3id.org/fio/v1/epa-frs-data#>

select ?o ?label where {
    epa-frs-data:d.FRS-Facility.110000428662 fio:ofIndustry ?o .
    ?o rdfs:label ?label.
} 


# FIO Basics
# CQ 5b
# Retrieve the NAICS Industry Codes of all facilities in NAICS sector 32.
# Works without relying on the fio:ofIndustry property chain axiom


PREFIX fio: <http://w3id.org/fio/v1/fio#>
PREFIX naics: <http://w3id.org/fio/v1/naics#> 

select * where {
    ?f fio:ofIndustry ?o .
    ?o fio:subcodeOf naics:NAICS-32 .
} limit 100

